const jugadores = [

	{
		player: 'Armani, Franco',
		camiseta: 1,
		valuacion: 6,
		posicion: 'Arquero',
		club: 'Club Atlético River Plate',
		partidos: 16,
		goles: 0,
		foto: 'imgs/armani.png',
	},
	{
		player: 'Acuña, Marcos',
		camiseta: 8,
		valuacion: 15,
		posicion: 'Defensor',
		club: 'Sevilla FC',
		partidos: 35,
		goles: 0,
		foto: 'imgs/macunia.png',
	},
	{
		player: 'Alvarez, Julián',
		camiseta: 27,
		valuacion: 15,
		posicion: 'Delantero',
		club: 'Club Atlético River Plate',
		partidos: 2,
		goles: 0,
		foto: 'imgs/jalvarez.png',
	},	
	{
		player: 'Correa, Ángel',
		camiseta: 9,
		valuacion: 40,
		posicion: 'Delantero',
		club: 'Atlético de Madrid',
		partidos: 17,
		goles: 3,
		foto: 'imgs/acorrea.png',
	},	
	{
		player: 'Correa, Joaquín',
		camiseta: 16,
		valuacion: 30,
		posicion: 'Delantero',
		club: 'Inter de Milán',
		partidos: 10,
		goles: 3,
		foto: 'imgs/jcorrea.png',
	},	
	{
		player: 'de Paul, Rodrigo',
		camiseta: 7,
		valuacion: 40,
		posicion: 'Mediocampista',
		club: 'Atlético de Madrid',
		partidos: 31,
		goles: 1,
		foto: 'imgs/depaul.png',
	},
	{
		player: 'Di Maria, Ángel',
		camiseta: 11,
		valuacion: 24,
		posicion: 'Delantero',
		club: 'Paris Saint Germain',
		partidos: 113,
		goles: 21,
		foto: 'imgs/dimaria.png',
	},
	{
		player: 'Dominguez, Nicolás',
		camiseta: 17,
		valuacion: 10,
		posicion: 'Mediocampista',
		club: 'Bolonia',
		partidos: 10,
		goles: 1,
		foto: 'imgs/ndominguez.png',
	},	
	{
		player: 'Dybala, Paulo',
		camiseta: 21,
		valuacion: 50,
		posicion: 'Delantero',
		club: 'Juventus de Turín',
		partidos: 30,
		goles: 2,
		foto: 'imgs/dybala.png',
	},	
	{
		player: 'Foyth, Juan',
		camiseta: 2,
		valuacion: 12,
		posicion: 'Defensor',
		club: 'Villarreal FC',
		partidos: 13,
		goles: 0,
		foto: 'imgs/foyth.png',
	},
	{
		player: 'Gómez, Alejandro Darío',
		camiseta: 17,
		valuacion: 9,
		posicion: 'Delantero',
		club: 'Sevilla FC',
		partidos: 8,
		goles: 3,
		foto: 'imgs/pgomez.png',
	},
	{
		player: 'Gonzalez, Nicolás',
		camiseta: 15,
		valuacion: 22,
		posicion: 'Delantero',
		club: 'Fiorentina',
		partidos: 12,
		goles: 2,
		foto: 'imgs/ngonzalez.png',
	},	
	{
		player: 'Lo Celso, Giovani',
		camiseta: 20,
		valuacion: 27,
		posicion: 'Mediocampista',
		club: 'Tottenham Hotspur',
		partidos: 31,
		goles: 2,
		foto: 'imgs/locelso.png',
	},	
	{
		player: 'Martinez, Emiliano',
		camiseta: 23,
		valuacion: 35,
		posicion: 'Arquero',
		club: 'Aston Villa',
		partidos: 9,
		goles: 0,
		foto: 'imgs/emartinez.png',
	},
	{
		player: 'Martinez, Lautaro',
		camiseta: 22,
		valuacion: 80,
		posicion: 'Delantero',
		club: 'Inter de Milán',
		partidos: 31,
		goles: 15,
		foto: 'imgs/lautaro.png',
	},		
	{
		player: 'Martinez, Lisandro',
		camiseta: 25,
		valuacion: 23,
		posicion: 'Defensor',
		club: 'Ajax de Ámsterdam',
		partidos: 3,
		goles: 0,
		foto: 'imgs/lmartinez.png',
	},
	{
		player: 'Martinez Quarta, Lucas',
		camiseta: 2,
		valuacion: 10,
		posicion: 'Defensor',
		club: 'Fiorentina',
		partidos: 9,
		goles: 0,
		foto: 'imgs/mquarta.png',
	},
	{
		player: 'Messi, Lionel',
		camiseta: 10,
		valuacion: 80,
		posicion: 'Delantero',
		club: 'Paris Saint Germain',
		partidos: 153,
		goles: 79,
		foto: 'imgs/messi.png',
	},
	{
		player: 'Molina, Nahuel',
		camiseta: 13,
		valuacion: 10,
		posicion: 'Defensor',
		club: 'Udinese',
		partidos: 8,
		goles: 0,
		foto: 'imgs/nmolina.png',
	},	
	{
		player: 'Montiel, Gonzalo',
		camiseta: 4,
		valuacion: 17,
		posicion: 'Defensor',
		club: 'Sevilla FC',
		partidos: 13,
		goles: 0,
		foto: 'imgs/montiel.png',
	},	
	{
		player: 'Musso, Juan',
		camiseta: 12,
		valuacion: 20,
		posicion: 'Arquero',
		club: 'Atalanta de Bérgamo',
		partidos: 2,
		goles: 0,
		foto: 'imgs/jmusso.png'
	},	
	{
		player: 'Otamendi, Nicolás',
		camiseta: 19,
		valuacion: 8,
		posicion: 'Defensor',
		club: 'SL Benfica',
		partidos: 83,
		goles: 4,
		foto: 'imgs/otamendi.png',
	},
	{
		player: 'Palacios, Exequiel',
		camiseta: 14,
		valuacion: 13,
		posicion: 'Mediocampista',
		club: 'Bayern 04 Leverkusen',
		partidos: 14,
		goles: 0,
		foto: 'imgs/epalacios.png',
	},
	{
		player: 'Paredes, Leandro',
		camiseta: 5,
		valuacion: 22,
		posicion: 'Mediocampista',
		club: 'Paris Saint Germain',
		partidos: 37,
		goles: 4,
		foto: 'imgs/paredes.png',
	},
	{
		player: 'Pezzella, Germán',
		camiseta: 6,
		valuacion: 7,
		posicion: 'Defensor',
		club: 'Real Betis Balompié',
		partidos: 25,
		goles: 2,
		foto: 'imgs/pezzella.png',
	},
	{
		player: 'Rodriguez, Guido',
		camiseta: 18,
		valuacion: 22,
		posicion: 'Mediocampista',
		club: 'Real Betis Balompié',
		partidos: 17,
		goles: 1,
		foto: 'imgs/grodriguez.png',
	},
	{
		player: 'Romero, Cristian',
		camiseta: 13,
		valuacion: 35,
		posicion: 'Defensor',
		club: 'Tottenham Hotspurs',
		partidos: 5,
		goles: 1,
		foto: 'imgs/romero.png',
	},
	{
		player: 'Rossi, Agustin',
		camiseta: 23,
		valuacion: 2,
		posicion: 'Arquero',
		club: 'Club Atlético Boca Juniors',
		partidos: 0,
		goles: 0,
		foto: 'imgs/arossi.png',
	},
	{
		player: 'Rulli, Geronimo',
		camiseta: 1,
		valuacion: 4,
		posicion: 'Arquero',
		club: 'Villarreal FC',
		partidos: 2,
		goles: 0,
		foto: 'imgs/jrulli.png',
	},
	{
		player: 'Tagliafico, Nicolás',
		camiseta: 3,
		valuacion: 22,
		posicion: 'Defensor',
		club: 'Ajax de Ámsterdam',
		partidos: 34,
		goles: 0,
		foto: 'imgs/tagliafico.png',
	},

	
];
